#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductListModule
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProductList")]
	public partial class ProductDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InsertProduct2(Product2 instance);
    partial void UpdateProduct2(Product2 instance);
    partial void DeleteProduct2(Product2 instance);
    #endregion
		
		public ProductDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProductListConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<Product2> Product2s
		{
			get
			{
				return this.GetTable<Product2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cat_id;
		
		private string _cat_type;
		
		private EntitySet<Product2> _Product2s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_idChanging(string value);
    partial void Oncat_idChanged();
    partial void Oncat_typeChanging(string value);
    partial void Oncat_typeChanged();
    #endregion
		
		public Category()
		{
			this._Product2s = new EntitySet<Product2>(new Action<Product2>(this.attach_Product2s), new Action<Product2>(this.detach_Product2s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_type", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string cat_type
		{
			get
			{
				return this._cat_type;
			}
			set
			{
				if ((this._cat_type != value))
				{
					this.Oncat_typeChanging(value);
					this.SendPropertyChanging();
					this._cat_type = value;
					this.SendPropertyChanged("cat_type");
					this.Oncat_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Product2", Storage="_Product2s", ThisKey="cat_id", OtherKey="prod_cat")]
		public EntitySet<Product2> Product2s
		{
			get
			{
				return this._Product2s;
			}
			set
			{
				this._Product2s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Product2s(Product2 entity)
		{
			this.SendPropertyChanging();
			entity.Category = this;
		}
		
		private void detach_Product2s(Product2 entity)
		{
			this.SendPropertyChanging();
			entity.Category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product2")]
	public partial class Product2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _prod_id;
		
		private string _prod_name;
		
		private decimal _prod_price;
		
		private string _prod_desc;
		
		private string _prod_img;
		
		private string _prod_cat;
		
		private System.Nullable<int> _stock_count;
		
		private System.Nullable<decimal> _weight;
		
		private System.Nullable<decimal> _width;
		
		private System.Nullable<decimal> _length;
		
		private System.Nullable<decimal> _height;
		
		private decimal _shipping_fee;
		
		private System.DateTime _created_at;
		
		private System.Nullable<System.DateTime> _updated_at;
		
		private string _prod_status;
		
		private EntityRef<Category> _Category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprod_idChanging(string value);
    partial void Onprod_idChanged();
    partial void Onprod_nameChanging(string value);
    partial void Onprod_nameChanged();
    partial void Onprod_priceChanging(decimal value);
    partial void Onprod_priceChanged();
    partial void Onprod_descChanging(string value);
    partial void Onprod_descChanged();
    partial void Onprod_imgChanging(string value);
    partial void Onprod_imgChanged();
    partial void Onprod_catChanging(string value);
    partial void Onprod_catChanged();
    partial void Onstock_countChanging(System.Nullable<int> value);
    partial void Onstock_countChanged();
    partial void OnweightChanging(System.Nullable<decimal> value);
    partial void OnweightChanged();
    partial void OnwidthChanging(System.Nullable<decimal> value);
    partial void OnwidthChanged();
    partial void OnlengthChanging(System.Nullable<decimal> value);
    partial void OnlengthChanged();
    partial void OnheightChanging(System.Nullable<decimal> value);
    partial void OnheightChanged();
    partial void Onshipping_feeChanging(decimal value);
    partial void Onshipping_feeChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    partial void Onprod_statusChanging(string value);
    partial void Onprod_statusChanged();
    #endregion
		
		public Product2()
		{
			this._Category = default(EntityRef<Category>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_id", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string prod_id
		{
			get
			{
				return this._prod_id;
			}
			set
			{
				if ((this._prod_id != value))
				{
					this.Onprod_idChanging(value);
					this.SendPropertyChanging();
					this._prod_id = value;
					this.SendPropertyChanged("prod_id");
					this.Onprod_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prod_name
		{
			get
			{
				return this._prod_name;
			}
			set
			{
				if ((this._prod_name != value))
				{
					this.Onprod_nameChanging(value);
					this.SendPropertyChanging();
					this._prod_name = value;
					this.SendPropertyChanged("prod_name");
					this.Onprod_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_price", DbType="Decimal(9,2) NOT NULL")]
		public decimal prod_price
		{
			get
			{
				return this._prod_price;
			}
			set
			{
				if ((this._prod_price != value))
				{
					this.Onprod_priceChanging(value);
					this.SendPropertyChanging();
					this._prod_price = value;
					this.SendPropertyChanged("prod_price");
					this.Onprod_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_desc", DbType="VarChar(120) NOT NULL", CanBeNull=false)]
		public string prod_desc
		{
			get
			{
				return this._prod_desc;
			}
			set
			{
				if ((this._prod_desc != value))
				{
					this.Onprod_descChanging(value);
					this.SendPropertyChanging();
					this._prod_desc = value;
					this.SendPropertyChanged("prod_desc");
					this.Onprod_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_img", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string prod_img
		{
			get
			{
				return this._prod_img;
			}
			set
			{
				if ((this._prod_img != value))
				{
					this.Onprod_imgChanging(value);
					this.SendPropertyChanging();
					this._prod_img = value;
					this.SendPropertyChanged("prod_img");
					this.Onprod_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_cat", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string prod_cat
		{
			get
			{
				return this._prod_cat;
			}
			set
			{
				if ((this._prod_cat != value))
				{
					if (this._Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprod_catChanging(value);
					this.SendPropertyChanging();
					this._prod_cat = value;
					this.SendPropertyChanged("prod_cat");
					this.Onprod_catChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_count", DbType="Int")]
		public System.Nullable<int> stock_count
		{
			get
			{
				return this._stock_count;
			}
			set
			{
				if ((this._stock_count != value))
				{
					this.Onstock_countChanging(value);
					this.SendPropertyChanging();
					this._stock_count = value;
					this.SendPropertyChanged("stock_count");
					this.Onstock_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_width", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> width
		{
			get
			{
				return this._width;
			}
			set
			{
				if ((this._width != value))
				{
					this.OnwidthChanging(value);
					this.SendPropertyChanging();
					this._width = value;
					this.SendPropertyChanged("width");
					this.OnwidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_length", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> length
		{
			get
			{
				return this._length;
			}
			set
			{
				if ((this._length != value))
				{
					this.OnlengthChanging(value);
					this.SendPropertyChanging();
					this._length = value;
					this.SendPropertyChanged("length");
					this.OnlengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipping_fee", DbType="Decimal(9,2) NOT NULL")]
		public decimal shipping_fee
		{
			get
			{
				return this._shipping_fee;
			}
			set
			{
				if ((this._shipping_fee != value))
				{
					this.Onshipping_feeChanging(value);
					this.SendPropertyChanging();
					this._shipping_fee = value;
					this.SendPropertyChanged("shipping_fee");
					this.Onshipping_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_status", DbType="NVarChar(MAX)")]
		public string prod_status
		{
			get
			{
				return this._prod_status;
			}
			set
			{
				if ((this._prod_status != value))
				{
					this.Onprod_statusChanging(value);
					this.SendPropertyChanging();
					this._prod_status = value;
					this.SendPropertyChanged("prod_status");
					this.Onprod_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Product2", Storage="_Category", ThisKey="prod_cat", OtherKey="cat_id", IsForeignKey=true)]
		public Category Category
		{
			get
			{
				return this._Category.Entity;
			}
			set
			{
				Category previousValue = this._Category.Entity;
				if (((previousValue != value) 
							|| (this._Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Category.Entity = null;
						previousValue.Product2s.Remove(this);
					}
					this._Category.Entity = value;
					if ((value != null))
					{
						value.Product2s.Add(this);
						this._prod_cat = value.cat_id;
					}
					else
					{
						this._prod_cat = default(string);
					}
					this.SendPropertyChanged("Category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
