<?xml version="1.0" encoding="utf-8"?><Database Name="ProductList" Class="ProductDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\ProductList.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProductListConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="cat_id" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cat_type" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product2" Member="Product2s" ThisKey="cat_id" OtherKey="prod_cat" Type="Product2" />
    </Type>
  </Table>
  <Table Name="dbo.Product2" Member="Product2s">
    <Type Name="Product2">
      <Column Name="prod_id" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="prod_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prod_price" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="prod_desc" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="prod_img" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="prod_cat" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="stock_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="weight" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="width" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="length" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="height" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="shipping_fee" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="prod_status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Category_Product2" Member="Category" ThisKey="prod_cat" OtherKey="cat_id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>